In [1]:
from sklearn.ensemble import RandomForestRegressor
RFR=RandomForestRegressor()

In [2]:
from sklearn.ensemble import RandomForestClassifier
RFR=RandomForestClassifier()

In [3]:
import warnings
warnings.filterwarnings('ignore')

In [4]:
import pandas as pd
Data=pd.read_csv('Diabetes.csv')
Data

Pregnancies  Glucose  BloodPressure  SkinThickness  Insulin   BMI  \
0              6      148             72             35        0  33.6   
1              1       85             66             29        0  26.6   
2              8      183             64              0        0  23.3   
3              1       89             66             23       94  28.1   
4              0      137             40             35      168  43.1   
..           ...      ...            ...            ...      ...   ...   
763           10      101             76             48      180  32.9   
764            2      122             70             27        0  36.8   
765            5      121             72             23      112  26.2   
766            1      126             60              0        0  30.1   
767            1       93             70             31        0  30.4   

     DiabetesPedigreeFunction  Age  Outcome  
0                       0.627   50        1  
1                       0.351   31        0  
2                       0.672   32        1  
3                       0.167   21        0  
4                       2.288   33        1  
..                        ...  ...      ...  
763                     0.171   63        0  
764                     0.340   27        0  
765                     0.245   30        0  
766                     0.349   47        1  
767                     0.315   23        0  

[768 rows x 9 columns]

In [5]:
import numpy as np
Data['Glucose']=np.where(Data['Glucose']==0,Data['Glucose'].median(),Data['Glucose'])
Data['Insulin']=np.where(Data['Insulin']==0,Data['Insulin'].median(),Data['Insulin'])

In [6]:
X=Data.drop('Outcome',axis=1)
y=Data['Outcome']

In [7]:
pd.DataFrame(X,columns=Data.columns[:-1])

Pregnancies  Glucose  BloodPressure  SkinThickness  Insulin   BMI  \
0              6    148.0             72             35     30.5  33.6   
1              1     85.0             66             29     30.5  26.6   
2              8    183.0             64              0     30.5  23.3   
3              1     89.0             66             23     94.0  28.1   
4              0    137.0             40             35    168.0  43.1   
..           ...      ...            ...            ...      ...   ...   
763           10    101.0             76             48    180.0  32.9   
764            2    122.0             70             27     30.5  36.8   
765            5    121.0             72             23    112.0  26.2   
766            1    126.0             60              0     30.5  30.1   
767            1     93.0             70             31     30.5  30.4   

     DiabetesPedigreeFunction  Age  
0                       0.627   50  
1                       0.351   31  
2                       0.672   32  
3                       0.167   21  
4                       2.288   33  
..                        ...  ...  
763                     0.171   63  
764                     0.340   27  
765                     0.245   30  
766                     0.349   47  
767                     0.315   23  

[768 rows x 8 columns]

In [8]:
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.20,random_state=0)

In [9]:
from sklearn.ensemble import RandomForestClassifier
RF_Classifier=RandomForestClassifier(n_estimators=10).fit(X_train,y_train)
Prediction=RF_Classifier.predict(X_test)

In [10]:
Prediction

array([1, 0, 0, 1, 0, 0, 1, 1, 0, 0, 1, 1, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0,
       0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 1, 0, 0, 1,
       0, 0, 0, 0, 1, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 1,
       1, 0, 1, 0, 0, 0, 0, 1, 1, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0,
       1, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 1, 0, 0, 0, 0, 1, 1, 0, 1, 0, 0,
       0, 0, 1, 1, 1, 1, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 1, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0],
      dtype=int64)

In [11]:
from sklearn.metrics import confusion_matrix,classification_report,accuracy_score
print(confusion_matrix(y_test,Prediction))
print(accuracy_score(y_test,Prediction))
print(classification_report(y_test,Prediction))

[[93 14]
 [19 28]]
0.7857142857142857
              precision    recall  f1-score   support

           0       0.83      0.87      0.85       107
           1       0.67      0.60      0.63        47

    accuracy                           0.79       154
   macro avg       0.75      0.73      0.74       154
weighted avg       0.78      0.79      0.78       154



In [12]:
# THE MAIN PARAMETERS USED BY A RANDOM FOREST CLASSIFIER ARE:
# criterion = THE FUNCTION USED TO EVALUATE THE QUALITY OF SPLIT
# max_depth = MAXIMUM NUMBER OF LEVELS ALLOWED IN EACH TREE
# max_features = MAXIMUM NUMBER OF FEATURES CONSIDERED WHEN SPLITTING A NODE
# min_samples_leaf = MINIMUM NUMBER OF SAMPLES THAT CAN BE STORED IN A TREE LEAF
# min_samples_split = MINIMUM NUMBER OF SAMPLES NECESSARY IN A NODE TO CAUSE NODE SPLITTING
# n_estimators = NUMBER OF TREES IN AN ENSEMBLE

In [13]:
# MANUAL HYPERPARAMETER TUNING
Model=RandomForestClassifier(n_estimators=300,criterion='entropy',
                             max_features='sqrt',min_samples_leaf=10,random_state=100).fit(X_train,y_train)
Prediction=Model.predict(X_test)
print(confusion_matrix(y_test,Prediction))
print(accuracy_score(y_test,Prediction))
print(classification_report(y_test,Prediction))

[[98  9]
 [18 29]]
0.8246753246753247
              precision    recall  f1-score   support

           0       0.84      0.92      0.88       107
           1       0.76      0.62      0.68        47

    accuracy                           0.82       154
   macro avg       0.80      0.77      0.78       154
weighted avg       0.82      0.82      0.82       154



In [14]:
import numpy as np
from sklearn.model_selection import RandomizedSearchCV
# NUMBER OF TREES IN A RANDOM FOREST
n_estimators = [int(x) for x in np.linspace(start = 200, stop = 2000, num = 10)]
# NUMBER OF FEATURES TO CONSIDER IN EVERY SPLIT
max_features = ['auto', 'sqrt','log2']
# MAXIMUM NUMBER OF LEVELS IN A TREE
max_depth = [int(x) for x in np.linspace(10, 1000,10)]
# MINIMUM NUMBER OF SAMPLES REQUIRED TO SPLIT A NODE
min_samples_split = [1,2,3,4,5,7,9]
# MINIMUM NUMBER OF SAMPLES REQUIRED AT EACH LEAF NODE
min_samples_leaf = [1,2,4,6,8]
# CREATE THE RANDOM GRID
Random_Grid = {'n_estimators': n_estimators,
               'max_features': max_features,
               'max_depth': max_depth,
               'min_samples_split': min_samples_split,
               'min_samples_leaf': min_samples_leaf,
              'criterion':['entropy','gini']}
print(Random_Grid)

{'n_estimators': [200, 400, 600, 800, 1000, 1200, 1400, 1600, 1800, 2000], 'max_features': ['auto', 'sqrt', 'log2'], 'max_depth': [10, 120, 230, 340, 450, 560, 670, 780, 890, 1000], 'min_samples_split': [1, 2, 3, 4, 5, 7, 9], 'min_samples_leaf': [1, 2, 4, 6, 8], 'criterion': ['entropy', 'gini']}


In [15]:
from sklearn.model_selection import RandomizedSearchCV

RF=RandomForestClassifier()
RF_Classifier=RandomizedSearchCV(estimator=RF,param_distributions=Random_Grid,n_iter=50,cv=3,verbose=2,
                               random_state=100,n_jobs=-1)
RF_Classifier.fit(X_train,y_train)

Fitting 3 folds for each of 50 candidates, totalling 150 fits


[Parallel(n_jobs=-1)]: Using backend LokyBackend with 8 concurrent workers.
[Parallel(n_jobs=-1)]: Done  25 tasks      | elapsed:   12.2s
[Parallel(n_jobs=-1)]: Done 150 out of 150 | elapsed:  1.9min finished


RandomizedSearchCV(cv=3, error_score=nan,
                   estimator=RandomForestClassifier(bootstrap=True,
                                                    ccp_alpha=0.0,
                                                    class_weight=None,
                                                    criterion='gini',
                                                    max_depth=None,
                                                    max_features='auto',
                                                    max_leaf_nodes=None,
                                                    max_samples=None,
                                                    min_impurity_decrease=0.0,
                                                    min_impurity_split=None,
                                                    min_samples_leaf=1,
                                                    min_samples_split=2,
                                                    min_weight_fraction_leaf=0.0,
               

In [16]:
RF_Classifier.best_params_

{'n_estimators': 600,
 'min_samples_split': 2,
 'min_samples_leaf': 2,
 'max_features': 'sqrt',
 'max_depth': 1000,
 'criterion': 'gini'}

In [18]:
RF_Classifier.best_estimator_

RandomForestClassifier(bootstrap=True, ccp_alpha=0.0, class_weight=None,
                       criterion='gini', max_depth=1000, max_features='sqrt',
                       max_leaf_nodes=None, max_samples=None,
                       min_impurity_decrease=0.0, min_impurity_split=None,
                       min_samples_leaf=2, min_samples_split=2,
                       min_weight_fraction_leaf=0.0, n_estimators=600,
                       n_jobs=None, oob_score=False, random_state=None,
                       verbose=0, warm_start=False)

In [19]:
Best_RF=RF_Classifier.best_estimator_

In [20]:
from sklearn.metrics import accuracy_score
y_pred=Best_RF.predict(X_test)
print(confusion_matrix(y_test,y_pred))
print("Accuracy Score {}".format(accuracy_score(y_test,y_pred)))
print("Classification report: {}".format(classification_report(y_test,y_pred)))

[[95 12]
 [14 33]]
Accuracy Score 0.8311688311688312
Classification report:               precision    recall  f1-score   support

           0       0.87      0.89      0.88       107
           1       0.73      0.70      0.72        47

    accuracy                           0.83       154
   macro avg       0.80      0.79      0.80       154
weighted avg       0.83      0.83      0.83       154



In [21]:
from sklearn.metrics import accuracy_score
y_pred=RF_Classifier.predict(X_test)
print(confusion_matrix(y_test,y_pred))
print("Accuracy Score {}".format(accuracy_score(y_test,y_pred)))
print("Classification report: {}".format(classification_report(y_test,y_pred)))

[[95 12]
 [14 33]]
Accuracy Score 0.8311688311688312
Classification report:               precision    recall  f1-score   support

           0       0.87      0.89      0.88       107
           1       0.73      0.70      0.72        47

    accuracy                           0.83       154
   macro avg       0.80      0.79      0.80       154
weighted avg       0.83      0.83      0.83       154



In [22]:
from sklearn.model_selection import GridSearchCV

Param_Grid = {
    'criterion': [RF_Classifier.best_params_['criterion']],
    'max_depth': [RF_Classifier.best_params_['max_depth']],
    'max_features': [RF_Classifier.best_params_['max_features']],
    'min_samples_leaf': [RF_Classifier.best_params_['min_samples_leaf'], 
                         RF_Classifier.best_params_['min_samples_leaf']+2, 
                         RF_Classifier.best_params_['min_samples_leaf'] + 4],
    'min_samples_split': [RF_Classifier.best_params_['min_samples_split'] - 2,
                          RF_Classifier.best_params_['min_samples_split'] - 1,
                          RF_Classifier.best_params_['min_samples_split'], 
                          RF_Classifier.best_params_['min_samples_split'] +1,
                          RF_Classifier.best_params_['min_samples_split'] + 2],
    'n_estimators': [RF_Classifier.best_params_['n_estimators'] - 200, RF_Classifier.best_params_['n_estimators'] - 100, 
                     RF_Classifier.best_params_['n_estimators'], 
                     RF_Classifier.best_params_['n_estimators'] + 100, RF_Classifier.best_params_['n_estimators'] + 200]
}

print(Param_Grid)

{'criterion': ['gini'], 'max_depth': [1000], 'max_features': ['sqrt'], 'min_samples_leaf': [2, 4, 6], 'min_samples_split': [0, 1, 2, 3, 4], 'n_estimators': [400, 500, 600, 700, 800]}


In [23]:
RFC=RandomForestClassifier()
Grid_Search=GridSearchCV(estimator=RFC,param_grid=Param_Grid,cv=5,n_jobs=-1,verbose=2)
Grid_Search.fit(X_train,y_train)

Fitting 5 folds for each of 75 candidates, totalling 375 fits


[Parallel(n_jobs=-1)]: Using backend LokyBackend with 8 concurrent workers.
[Parallel(n_jobs=-1)]: Done  25 tasks      | elapsed:    7.4s
[Parallel(n_jobs=-1)]: Done 146 tasks      | elapsed:   57.8s
[Parallel(n_jobs=-1)]: Done 349 tasks      | elapsed:  2.2min
[Parallel(n_jobs=-1)]: Done 375 out of 375 | elapsed:  2.5min finished


GridSearchCV(cv=5, error_score=nan,
             estimator=RandomForestClassifier(bootstrap=True, ccp_alpha=0.0,
                                              class_weight=None,
                                              criterion='gini', max_depth=None,
                                              max_features='auto',
                                              max_leaf_nodes=None,
                                              max_samples=None,
                                              min_impurity_decrease=0.0,
                                              min_impurity_split=None,
                                              min_samples_leaf=1,
                                              min_samples_split=2,
                                              min_weight_fraction_leaf=0.0,
                                              n_estimators=100, n_jobs=None,
                                              oob_score=False,
                                              rando

In [24]:
Grid_Search.best_params_

{'criterion': 'gini',
 'max_depth': 1000,
 'max_features': 'sqrt',
 'min_samples_leaf': 6,
 'min_samples_split': 4,
 'n_estimators': 500}

In [26]:
Grid_Search.best_estimator_

RandomForestClassifier(bootstrap=True, ccp_alpha=0.0, class_weight=None,
                       criterion='gini', max_depth=1000, max_features='sqrt',
                       max_leaf_nodes=None, max_samples=None,
                       min_impurity_decrease=0.0, min_impurity_split=None,
                       min_samples_leaf=6, min_samples_split=4,
                       min_weight_fraction_leaf=0.0, n_estimators=500,
                       n_jobs=None, oob_score=False, random_state=None,
                       verbose=0, warm_start=False)

In [28]:
y_pred=Grid_Search.predict(X_test)
print(confusion_matrix(y_test,y_pred))
print("Accuracy Score {}".format(accuracy_score(y_test,y_pred)))
print("Classification report: {}".format(classification_report(y_test,y_pred)))

[[97 10]
 [17 30]]
Accuracy Score 0.8246753246753247
Classification report:               precision    recall  f1-score   support

           0       0.85      0.91      0.88       107
           1       0.75      0.64      0.69        47

    accuracy                           0.82       154
   macro avg       0.80      0.77      0.78       154
weighted avg       0.82      0.82      0.82       154



In [29]:
# AUTOMATED HYPERPARAMETER TUNINING

In [50]:
from hyperopt import hp,fmin,tpe,STATUS_OK,Trials

In [31]:
# 1.BAYESIAN OPTIMIZATION: THEY USES PROBABILITY TO FIND THE MINIMUM OF A FUNCTION. AIM:TO FIND THE INPUT VALUE OF A FUNCTION WHICH CAN GIVE THE LOWEST OUTPUT POSSIBLE,BETTER THAN ALL GRIDS FOR PROVIDING BETTER PERFORMANCE AND IN THE TESTING PHASE AND REDUCED OPTMIZATION TIME
# THREE MAIN PARAMETERS:
# 1.OBJECTIVE FUNCTION:THE LOSS FUNCTION TO MINIMIZE
# 2.DOMAIN SPACE:THE RANGE OF INPUT VALUES TO TEST
# 3.OPTIMIZATION ALGORITHM:DEFINES THE SEARCH ALGORITHM TO SELECT THE BEST INPUT VALUES TO USE IN EACH COLUMN

In [32]:
Params = {'criterion': hp.choice('criterion', ['entropy', 'gini']),
        'max_depth': hp.quniform('max_depth', 10, 1200, 10),
        'max_features': hp.choice('max_features', ['auto', 'sqrt','log2', None]),
        'min_samples_leaf': hp.uniform('min_samples_leaf', 0, 0.5),
        'min_samples_split' : hp.uniform ('min_samples_split', 0, 1),
        'n_estimators' : hp.choice('n_estimators', [10, 50, 300, 750, 1200,1300,1500])
        }

In [33]:
Params

{'criterion': <hyperopt.pyll.base.Apply at 0x1f86a63f5c8>,
 'max_depth': <hyperopt.pyll.base.Apply at 0x1f86a721cc8>,
 'max_features': <hyperopt.pyll.base.Apply at 0x1f86a71c848>,
 'min_samples_leaf': <hyperopt.pyll.base.Apply at 0x1f86a71c288>,
 'min_samples_split': <hyperopt.pyll.base.Apply at 0x1f86a71c888>,
 'n_estimators': <hyperopt.pyll.base.Apply at 0x1f86a70aa88>}

In [56]:
def Objective(Params):
    Model = RandomForestClassifier(criterion = Params['criterion'], max_depth = Params['max_depth'],
                                 max_features = Params['max_features'],
                                 min_samples_leaf = Params['min_samples_leaf'],
                                 min_samples_split = Params['min_samples_split'],
                                 n_estimators = Params['n_estimators'], 
                                 )
    
    Accuracy = cross_val_score(Model, X_train, y_train, cv=5).mean()
    # AFTER 5 ITERACTIONS,WE WANT TO GET THE MEAN OF ACCURACY OF 5 ITERACTIONS

    # WE WANT TO MAXIMIZE ACCURACY,THEREFORE WE RETURN NEGATIVE VALUES
    return {'loss': -Accuracy, 'status': STATUS_OK }


In [57]:
from sklearn.model_selection import cross_val_score
trials=Trials()
Best = fmin(fn= Objective,
            space=Params,
            algo= tpe.suggest,
            max_evals = 80,
            trials= trials
           )

100%|███████████████████████████████████████████████| 80/80 [08:03<00:00,  6.04s/trial, best loss: -0.7606157536985206]


In [58]:
Best

{'criterion': 0,
 'max_depth': 1040.0,
 'max_features': 3,
 'min_samples_leaf': 0.018901231796376372,
 'min_samples_split': 0.003914406799308046,
 'n_estimators': 0}

In [60]:
Criterion = {0: 'entropy', 1: 'gini'}
Feature = {0: 'auto', 1: 'sqrt', 2: 'log2', 3: None}
Estimator = {0: 10, 1: 50, 2: 300, 3: 750, 4: 1200,5:1300,6:1500}


print(Criterion[Best['criterion']])
print(Feature[Best['max_features']])
print(Estimator[Best['n_estimators']])

entropy
None
10


In [61]:
RFC = RandomForestClassifier(criterion = Criterion[Best['criterion']], max_depth = Best['max_depth'], 
                                       max_features = Feature[Best['max_features']], 
                                       min_samples_leaf = Best['min_samples_leaf'], 
                                       min_samples_split = Best['min_samples_split'], 
                                       n_estimators = Estimator[Best['n_estimators']]).fit(X_train,y_train)
Predicted = RFC.predict(X_test)
print(confusion_matrix(y_test,Predicted))
print(accuracy_score(y_test,Predicted))
print(classification_report(y_test,Predicted))
Accuracy = accuracy_score(y_test,Predicted)

[[96 11]
 [15 32]]
0.8311688311688312
              precision    recall  f1-score   support

           0       0.86      0.90      0.88       107
           1       0.74      0.68      0.71        47

    accuracy                           0.83       154
   macro avg       0.80      0.79      0.80       154
weighted avg       0.83      0.83      0.83       154

