In [1]:
import pandas as pd
import numpy as np

In [2]:
Data=pd.read_csv("Credit_Card.csv")

In [3]:
Data

Time         V1         V2        V3        V4        V5  \
0            0.0  -1.359807  -0.072781  2.536347  1.378155 -0.338321   
1            0.0   1.191857   0.266151  0.166480  0.448154  0.060018   
2            1.0  -1.358354  -1.340163  1.773209  0.379780 -0.503198   
3            1.0  -0.966272  -0.185226  1.792993 -0.863291 -0.010309   
4            2.0  -1.158233   0.877737  1.548718  0.403034 -0.407193   
...          ...        ...        ...       ...       ...       ...   
284802  172786.0 -11.881118  10.071785 -9.834783 -2.066656 -5.364473   
284803  172787.0  -0.732789  -0.055080  2.035030 -0.738589  0.868229   
284804  172788.0   1.919565  -0.301254 -3.249640 -0.557828  2.630515   
284805  172788.0  -0.240440   0.530483  0.702510  0.689799 -0.377961   
284806  172792.0  -0.533413  -0.189733  0.703337 -0.506271 -0.012546   

              V6        V7        V8        V9  ...       V21       V22  \
0       0.462388  0.239599  0.098698  0.363787  ... -0.018307  0.277838   
1      -0.082361 -0.078803  0.085102 -0.255425  ... -0.225775 -0.638672   
2       1.800499  0.791461  0.247676 -1.514654  ...  0.247998  0.771679   
3       1.247203  0.237609  0.377436 -1.387024  ... -0.108300  0.005274   
4       0.095921  0.592941 -0.270533  0.817739  ... -0.009431  0.798278   
...          ...       ...       ...       ...  ...       ...       ...   
284802 -2.606837 -4.918215  7.305334  1.914428  ...  0.213454  0.111864   
284803  1.058415  0.024330  0.294869  0.584800  ...  0.214205  0.924384   
284804  3.031260 -0.296827  0.708417  0.432454  ...  0.232045  0.578229   
284805  0.623708 -0.686180  0.679145  0.392087  ...  0.265245  0.800049   
284806 -0.649617  1.577006 -0.414650  0.486180  ...  0.261057  0.643078   

             V23       V24       V25       V26       V27       V28  Amount  \
0      -0.110474  0.066928  0.128539 -0.189115  0.133558 -0.021053  149.62   
1       0.101288 -0.339846  0.167170  0.125895 -0.008983  0.014724    2.69   
2       0.909412 -0.689281 -0.327642 -0.139097 -0.055353 -0.059752  378.66   
3      -0.190321 -1.175575  0.647376 -0.221929  0.062723  0.061458  123.50   
4      -0.137458  0.141267 -0.206010  0.502292  0.219422  0.215153   69.99   
...          ...       ...       ...       ...       ...       ...     ...   
284802  1.014480 -0.509348  1.436807  0.250034  0.943651  0.823731    0.77   
284803  0.012463 -1.016226 -0.606624 -0.395255  0.068472 -0.053527   24.79   
284804 -0.037501  0.640134  0.265745 -0.087371  0.004455 -0.026561   67.88   
284805 -0.163298  0.123205 -0.569159  0.546668  0.108821  0.104533   10.00   
284806  0.376777  0.008797 -0.473649 -0.818267 -0.002415  0.013649  217.00   

        Class  
0           0  
1           0  
2           0  
3           0  
4           0  
...       ...  
284802      0  
284803      0  
284804      0  
284805      0  
284806      0  

[284807 rows x 31 columns]

In [4]:
Data.isnull().sum()

Time      0
V1        0
V2        0
V3        0
V4        0
V5        0
V6        0
V7        0
V8        0
V9        0
V10       0
V11       0
V12       0
V13       0
V14       0
V15       0
V16       0
V17       0
V18       0
V19       0
V20       0
V21       0
V22       0
V23       0
V24       0
V25       0
V26       0
V27       0
V28       0
Amount    0
Class     0
dtype: int64

In [5]:
Data['Class'].value_counts()

0    284315
1       492
Name: Class, dtype: int64

In [6]:
X=Data.drop('Class',axis=1)
y=Data['Class']

In [7]:
from sklearn.ensemble import RandomForestClassifier
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score,confusion_matrix,classification_report

In [8]:
# 1.CROSS VALIDATION AND KFOLD

In [9]:
from sklearn.model_selection import KFold
from sklearn.model_selection import GridSearchCV

In [10]:
LR=LogisticRegression()
Grid={'C':10.0 **np.arange(-2,3),'penalty':['l1','l2']}
CV=KFold(n_splits=5,random_state=None,shuffle=False)

In [11]:
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test=train_test_split(X,y,train_size=0.7)

In [12]:
CLF=GridSearchCV(LR,Grid,cv=CV,n_jobs=-1,scoring='f1_macro')
CLF.fit(X_train,y_train)

C:\ProgramData\Anaconda3\lib\site-packages\sklearn\linear_model\_logistic.py:764: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  extra_warning_msg=_LOGISTIC_SOLVER_CONVERGENCE_MSG)


GridSearchCV(cv=KFold(n_splits=5, random_state=None, shuffle=False),
             estimator=LogisticRegression(), n_jobs=-1,
             param_grid={'C': array([1.e-02, 1.e-01, 1.e+00, 1.e+01, 1.e+02]),
                         'penalty': ['l1', 'l2']},
             scoring='f1_macro')

In [13]:
y_pred=CLF.predict(X_test)
y_pred

array([0, 0, 0, ..., 0, 0, 0], dtype=int64)

In [14]:
print(confusion_matrix(y_test,y_pred))
print(accuracy_score(y_test,y_pred))
print(classification_report(y_test,y_pred))

[[85252    41]
 [   52    98]]
0.9989115550718023
              precision    recall  f1-score   support

           0       1.00      1.00      1.00     85293
           1       0.71      0.65      0.68       150

    accuracy                           1.00     85443
   macro avg       0.85      0.83      0.84     85443
weighted avg       1.00      1.00      1.00     85443



In [15]:
# 2.CLASS WEIGHTS IN ENSEMBLE

In [16]:
Data=pd.read_csv('Credit_Card.csv',nrows=10000)

In [17]:
Data

Time        V1        V2        V3        V4        V5        V6  \
0         0 -1.359807 -0.072781  2.536347  1.378155 -0.338321  0.462388   
1         0  1.191857  0.266151  0.166480  0.448154  0.060018 -0.082361   
2         1 -1.358354 -1.340163  1.773209  0.379780 -0.503198  1.800499   
3         1 -0.966272 -0.185226  1.792993 -0.863291 -0.010309  1.247203   
4         2 -1.158233  0.877737  1.548718  0.403034 -0.407193  0.095921   
...     ...       ...       ...       ...       ...       ...       ...   
9995  15001  1.178755  0.596025  0.074131  2.542393  0.450685 -0.179355   
9996  15004  1.228455  0.049488  1.022099  0.386471 -0.973228 -1.067822   
9997  15008 -0.971734  0.744625  2.334822 -0.408046 -0.999231 -0.629294   
9998  15010 -1.529666  1.475870  1.507624 -0.662935 -1.037152 -1.159860   
9999  15012 -1.181721  1.485264  1.958715  2.587943 -0.504092 -0.126697   

            V7        V8        V9  ...       V21       V22       V23  \
0     0.239599  0.098698  0.363787  ... -0.018307  0.277838 -0.110474   
1    -0.078803  0.085102 -0.255425  ... -0.225775 -0.638672  0.101288   
2     0.791461  0.247676 -1.514654  ...  0.247998  0.771679  0.909412   
3     0.237609  0.377436 -1.387024  ... -0.108300  0.005274 -0.190321   
4     0.592941 -0.270533  0.817739  ... -0.009431  0.798278 -0.137458   
...        ...       ...       ...  ...       ...       ...       ...   
9995  0.326365 -0.234949  0.473040  ... -0.228112 -0.561559 -0.182781   
9996 -0.383162 -0.205407  1.699304  ... -0.322912 -0.730294  0.205601   
9997 -0.377212  0.481230  1.599496  ... -0.116821 -0.141219 -0.026115   
9998 -0.303219  0.745766  0.946896  ... -0.197993 -0.634088  0.100631   
9999  0.939038  0.175638 -0.756318  ... -0.010641 -0.191361  0.204004   

           V24       V25       V26       V27       V28  Amount  Class  
0     0.066928  0.128539 -0.189115  0.133558 -0.021053  149.62      0  
1    -0.339846  0.167170  0.125895 -0.008983  0.014724    2.69      0  
2    -0.689281 -0.327642 -0.139097 -0.055353 -0.059752  378.66      0  
3    -1.175575  0.647376 -0.221929  0.062723  0.061458  123.50      0  
4     0.141267 -0.206010  0.502292  0.219422  0.215153   69.99      0  
...        ...       ...       ...       ...       ...     ...    ...  
9995 -0.523241  0.667142  0.015699 -0.067238  0.008709   53.19      0  
9996  0.686302 -0.071008  0.729846 -0.092276  0.012277   12.18      0  
9997  0.712719 -0.372964  0.750323 -0.107875  0.031272    4.05      0  
9998  0.669449 -0.269750  0.611964 -0.169789  0.007846    4.05      0  
9999  0.663928  0.288780 -0.033612 -0.142682  0.028149  159.28      0  

[10000 rows x 31 columns]

In [18]:
Data['Class'].value_counts()

0    9962
1      38
Name: Class, dtype: int64

In [19]:
# EXAMPLE: 0--->10000 1---->100 SO, 1:100 (GIVE 100 TIMES LESS IMPORTANT TO ZERO ONES)
# Class_Weight=dict({0:1,1:100})
from sklearn.ensemble import RandomForestClassifier
Classifier=RandomForestClassifier(class_weight="balanced")

In [20]:
X=Data.drop('Class',axis=1)
y=Data['Class']

In [21]:
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test=train_test_split(X,y,train_size=0.7)

In [22]:
Classifier.fit(X_train,y_train)

RandomForestClassifier(class_weight='balanced')

In [23]:
y_pred=Classifier.predict(X_test)
print(confusion_matrix(y_test,y_pred))
print(accuracy_score(y_test,y_pred))
print(classification_report(y_test,y_pred))

[[2990    0]
 [   2    8]]
0.9993333333333333
              precision    recall  f1-score   support

           0       1.00      1.00      1.00      2990
           1       1.00      0.80      0.89        10

    accuracy                           1.00      3000
   macro avg       1.00      0.90      0.94      3000
weighted avg       1.00      1.00      1.00      3000

